name: "SEO Check"

on:
  push:
  workflow_dispatch:

jobs:
  registry-check:
    runs-on: ubuntu-latest
    steps:
      - name: Check registry reachability
        run: |
          resolvectl status
          sudo apt-get update
          curl https://gitlab.opencode.de -vvv || true
          echo "=== DNS lookup (default resolver) ==="
          dig registry.opencode.de || true
          echo "=== DNS lookup (Google 8.8.8.8) ==="
          dig @8.8.8.8 registry.opencode.de || true
          echo "=== DNSSEC check ==="
          dig @8.8.8.8 registry.opencode.de +dnssec || true
          echo "=== Trace route ==="
          echo "=== curl ==="
          curl -vI https://registry.opencode.de/v2/ 2>&1 || true

  seo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Limit Docker pull concurrency
        run: |
          sudo mkdir -p /etc/docker
          echo '{"max-concurrent-downloads":1}' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Run SEO-Check
        run: |
            set -x
        
            echo "DNS:"
            getent ahosts registry.opencode.de || true
        
            echo "IPv4 TLS:"
            curl -4 -v --connect-timeout 15 https://registry.opencode.de/v2/ || true
        
            echo "IPv6 TLS:"
            curl -6 -v --connect-timeout 15 https://registry.opencode.de/v2/ || true
        
            echo "TLS handshake timing:"
            time openssl s_client -connect registry.opencode.de:443 -servername registry.opencode.de </dev/null || true

            echo "DNS:"
            getent ahosts s3b.wx-one.com || true


            curl -4 -v --connect-timeout 15 https://oc-registry.s3d.wx1.eu || true
        
            echo "IPv4 TLS:"
            curl -4 -v --connect-timeout 15 https://s3b.wx-one.com/v2/ || true
        
            echo "IPv6 TLS:"
            curl -6 -v --connect-timeout 15 https://s3b.wx-one.com/v2/ || true
        
            echo "TLS handshake timing:"
            time openssl s_client -connect s3b.wx-one.com:443 -servername s3b.wx-one.com </dev/null || true

              
        
            echo "Docker version:"
            docker version

            docker pull registry.opencode.de/plain/oci/elasticsearch:8.19.9
            docker run --rm -v ${{ github.workspace }}:/workspace -w /workspace registry.opencode.de/open-code/document-writing-tools/seo-check:main-amd64
